export const galleryAttributions = [
  {
    title: "A group of colorful plates",
    url: "https://unsplash.com/photos/a-group-of-colorful-plates-P0fElPeUd0M",
    author: "Dmitriy Efimov",
    profile: "https://unsplash.com/@deeurbn",
  },
  {
    title: "Traditional Uzbekistan device for bread",
    url: "https://unsplash.com/photos/black-and-brown-wooden-spool-zknX3A2HdUI",
    author: "Artem Asset",
    profile: "https://unsplash.com/@aseevart",
  },
  {
    title: "A bunch of traditional Uzbek breads",
    url: "https://unsplash.com/photos/a-bunch-of-breads-that-are-sitting-on-a-table-rXPKelZmS_Q",
    author: "Evgeny Matveev",
    profile: "https://unsplash.com/@eugene_rus",
  },
  {
    title: "A group of colorful bowls",
    url: "https://unsplash.com/photos/a-group-of-colorful-bowls-Sx7WpkDElKM",
    author: "Safar Safarov",
    profile: "https://unsplash.com/@safarslife",
  },
  {
    title: "Samsa on a tray",
    url: "https://unsplash.com/photos/brown-bread-on-stainless-steel-tray-6hMFtsD2up4",
    author: "Tamara Malaniy",
    profile: "https://unsplash.com/@tamarushphotos",
  },
  {
    title: "A person holding a piece of bread",
    url: "https://unsplash.com/photos/a-person-holding-a-piece-of-bread-on-top-of-a-table-iJmoo8Hct0U",
    author: "Joel Herd",
    profile: "https://unsplash.com/@kazheard",
  },
  {
    title: "Colourful spices sold in Chorsu Bazaar, Tashkent, Uzbekistan",
    url: "https://unsplash.com/photos/jack-daniels-old-no-7-brand--9jMMaNuhOk",
    author: "Zuyet Awarmatik",
    profile: "https://unsplash.com/@zuyetawarmatik",
  },
  {
    title: "Samarkand Architecture",
    url: "https://unsplash.com/photos/a-large-ornate-building-with-a-dome-hvLu3ABC1n0",
    author: "Ozodbek Erkinov",
    profile: "https://unsplash.com/@demac_csgo",
  },
  {
    title: "Marifat mosque in Zaamin, Jizzakh",
    url: "https://unsplash.com/photos/blue-and-gold-floral-ceiling-lpmpsETf2BQ",
    author: "Farhodjon Chinberdiev",
    profile: "https://unsplash.com/@far5n10v",
  },
  {
    title: "Golden plums on a tree",
    url: "https://www.pexels.com/photo/ripe-golden-plums-on-tree-under-blue-sky-33190833/",
    author: "Nurkamol Vakhidov",
    profile: "https://www.pexels.com/@nurkamol/",
  },
  {
    title: "Mir i Arab Madrasa in Bukhara",
    url: "https://www.pexels.com/photo/mir-i-arab-madrasa-in-bukhara-19439119/",
    author: "AXP Photography",
    profile: "https://www.pexels.com/@axp-photography-500641970/",
  },
  {
    title: "Uzbek Samsas on a Wooden Coaster",
    url: "https://www.pexels.com/photo/uzbek-samsas-on-a-wooden-coaster-16260568/",
    author: "Nadin Sh",
    profile: "https://www.pexels.com/@nadin-sh-78971847/",
  },
  {
    title: "Close-up of samsa",
    url: "https://www.pexels.com/photo/close-up-of-samsa-14286677/",
    author: "Nadin Sh",
    profile: "https://www.pexels.com/@nadin-sh-78971847/",
  },
  {
    title: "Fresh baked bread",
    url: "https://unsplash.com/photos/fresh-baked-bread-on-display-at-market-Mx1tUbdRUec",
    author: "Dasha Novikova",
    profile: "https://unsplash.com/@dashanovasha",
  },
  {
    title: "Butternut squash pile",
    url: "https://unsplash.com/photos/a-large-pile-of-butternut-squash-1-Y1vTpRcjo",
    author: "Dasha Novikova",
    profile: "https://unsplash.com/@dashanovasha",
  },
  {
    title: "A woman walks past a colorful fruit stand",
    url: "https://unsplash.com/photos/a-woman-walks-past-a-colorful-fruit-stand-BRbdYUUhOlI",
    author: "Dasha Novikova",
    profile: "https://unsplash.com/@dashanovasha",
  },
];

export const quizAttributions = [
  {
    title: "Spices in bowls",
    url: "https://unsplash.com/photos/stainless-steel-bowls-2IaZGfBKgMY",
    author: "Json Leung",
    profile: "https://unsplash.com/@ninjason",
  },
  {
    title: "Ceramic plates on wall",
    url: "https://unsplash.com/photos/a-room-filled-with-lots-of-different-types-of-plates-TpjvNsI_h_0",
    author: "Pramod Kumar Sharma",
    profile: "https://unsplash.com/@pksindia",
  },
  {
    title: "Colorful crocheted rugs",
    url: "https://unsplash.com/photos/a-pile-of-multicolored-crocheted-rugs-sitting-on-top-of-each-4RNMungWX14",
    author: "Tomasz Anusiewicz",
    profile: "https://unsplash.com/@oxganggreen",
  },
  {
    title: "Tea with teapot",
    url: "https://unsplash.com/photos/clear-glass-cup-with-tea-near-brown-ceramic-teapot-L82-kkEBOd0",
    author: "Manki Kim",
    profile: "https://unsplash.com/@kimdonkey",
  },
  {
    title: "Cutting bread for breakfast",
    url: "https://unsplash.com/photos/a-person-cutting-bread-on-a-cutting-board-GbdXzU12-PA",
    author: "frogses production",
    profile: "https://unsplash.com/@frogses",
  },
  {
    title: "Person journaling",
    url: "https://unsplash.com/photos/person-writing-on-a-book-fMD_Cru6OTk",
    author: "Cathryn Lavery",
    profile: "https://unsplash.com/@cathrynlavery",
  },
  {
    title: "Red chili peppers",
    url: "https://unsplash.com/photos/red-chili-peppers-sFU3-fwZ6nQ",
    author: "Elle Hughes",
    profile: "https://unsplash.com/@elletakesphotos",
  },
  {
    title: "Cumin in steel bowl",
    url: "https://unsplash.com/photos/brown-and-black-beans-in-stainless-steel-bowl-iwo-ItMFK0A",
    author: "Tamara Gak",
    profile: "https://unsplash.com/@tamara_photography",
  },
  {
    title: "Cinnamon sticks",
    url: "https://unsplash.com/photos/cinnamon-sticks-and-cinnamon-powder-on-a-table-Xvjs1G812Yo",
    author: "Rens D",
    profile: "https://unsplash.com/@rens23",
  },
  {
    title: "Garlic cloves",
    url: "https://unsplash.com/photos/garlic-lot-ZnYs2sGzfvo",
    author: "Joey Huang",
    profile: "https://unsplash.com/@onice",
  },
  {
    title: "Woman meditating on dock",
    url: "https://unsplash.com/photos/woman-in-black-tank-top-sitting-on-brown-wooden-dock-during-daytime-xce530fBHrk",
    author: "Jared Rice",
    profile: "https://unsplash.com/@jareddrice",
  },
  {
    title: "Eagle close-up",
    url: "https://unsplash.com/photos/brown-and-white-eagle-in-close-up-photography-qkZk_btKwpo",
    author: "Mark Timberlake",
    profile: "https://unsplash.com/@mtimber71",
  },
  {
    title: "Pumpkin soup with lemon",
    url: "https://unsplash.com/photos/soup-with-sliced-lemon-on-white-ceramic-bowl-TvEyo2WEzVE",
    author: "Ruth Georgiev",
    profile: "https://unsplash.com/@ruthgeorgiev",
  },
  {
    title: "Mint tea in glass",
    url: "https://unsplash.com/photos/clear-glass-mug-with-green-leaves-9T5FvfnmH_k",
    author: "Laårk Boshoff",
    profile: "https://unsplash.com/@laarkstudio",
  },
  {
    title: "Ginger tea with lemon",
    url: "https://unsplash.com/photos/a-cup-of-tea-with-lemon-and-ginger-on-a-wooden-table-PhsqOFCNDIg",
    author: "Kelly Sikkema",
    profile: "https://unsplash.com/@kellysikkema",
  },
  {
    title: "Petals in tea jar",
    url: "https://unsplash.com/photos/selective-focus-photography-of-petals-inside-glass-jar-88hxLwf6UHE",
    author: "freestocks",
    profile: "",
  },
  {
    title: "Cozy bed with coffee and book",
    url: "https://unsplash.com/photos/a-cup-of-coffee-and-a-book-on-a-bed-OI47P-7TtBc",
    author: "Galina Kondratenko",
    profile: "https://unsplash.com/@paralisart",
  },
  {
    title: "Spiral staircase near white wooden door",
    url: "https://unsplash.com/photos/empty-spiral-staircase-near-white-wooden-door-uY2kic9wlmc",
    author: "Eduard",
    profile: "https://unsplash.com/@eduardmilitaru",
  },
  {
    title: "Minimalist desk with plant",
    url: "https://unsplash.com/photos/white-desk-lamp-beside-green-plant-BlIhVfXbi9s",
    author: "Samantha Gades",
    profile: "https://unsplash.com/@srosinger3997",
  },
  {
    title: "Bold interior at coffee shop",
    url: "https://unsplash.com/photos/inside-tasman-coffee-shop-wv4MAewhXXc",
    author: "Let's go Together",
    profile: "https://unsplash.com/@lets_go_together",
  },
  {
    title: "Yellow tulips in glass vase",
    url: "https://unsplash.com/photos/yellow-tulips-in-clear-glass-vase-den6gTowZKs",
    author: "Nadir sYzYgY",
    profile: "https://unsplash.com/@nadir_syzygy",
  },
  {
    title: "A bird sitting on top of a statue of a man",
    url: "https://unsplash.com/photos/a-bird-sitting-on-top-of-a-statue-of-a-man-39eKd8qUsK0",
    author: "Joseph Corl",
    profile: "https://unsplash.com/@jcorl",
  },
  {
    title: "White and brown cat",
    url: "https://unsplash.com/photos/shallow-focus-photography-of-white-and-brown-cat-GtwiBmtJvaU",
    author: "Yerlin Matu",
    profile: "https://unsplash.com/@yerlinmatu",
  },
  {
    title: "Woman jumping on green hills",
    url: "https://unsplash.com/photos/woman-jumping-on-green-mountains-LEgwEaBVGMo",
    author: "Peter Conlan",
    profile: "https://unsplash.com/@peterconlan",
  },
];
