import { PieType } from "@/generated/prisma";
import { Question } from "@/types/quiz.types";

export const questions: Question[] = [
  {
    id: 1,
    questionKey: "question1",
    answerOptions: [
      {
        id: 1,
        answerKey: "q1a1",
        pieType: PieType.CLASSIC,
        imageUrl: "/images/question1/spices.avif",
        imageAlt: "Spices in bowls",
      },
      {
        id: 2,
        answerKey: "q1a2",
        pieType: PieType.PUMPKIN,
        imageUrl: "/images/question1/handicraft.avif",
        imageAlt: "Handmade crafts and threads",
      },
      {
        id: 3,
        answerKey: "q1a3",
        pieType: PieType.POTATO,
        imageUrl: "/images/question1/fruits.avif",
        imageAlt: "Fruits in a market",
      },
      {
        id: 4,
        answerKey: "q1a4",
        pieType: PieType.CHEESE,
        imageUrl: "/images/question1/ceramics.avif",
        imageAlt: "Colorful pottery",
      },
    ],
  },
  {
    id: 2,
    questionKey: "question2",
    answerOptions: [
      {
        id: 1,
        answerKey: "q2a1",
        pieType: PieType.CLASSIC,
        imageUrl: "/images/question2/tea.avif",
        imageAlt: "A teapot and a cup",
      },
      {
        id: 2,
        answerKey: "q2a2",
        pieType: PieType.POTATO,
        imageUrl: "/images/question2/breakfast.avif",
        imageAlt: "Bread, eggs and butter on the table",
      },
      {
        id: 3,
        answerKey: "q2a3",
        pieType: PieType.PUMPKIN,
        imageUrl: "/images/question2/journaling.avif",
        imageAlt: "Notebook and pen",
      },
      {
        id: 4,
        answerKey: "q2a4",
        pieType: PieType.CHEESE,
        imageUrl: "/images/question2/cleaning-and-dancing.jpg",
        imageAlt: "Person dancing with a mop",
      },
    ],
  },
  {
    id: 3,
    questionKey: "question3",
    answerOptions: [
      {
        id: 1,
        answerKey: "q3a1",
        pieType: PieType.LAMB,
        imageUrl: "/images/question3/chili.avif",
        imageAlt: "Chili peppers",
      },
      {
        id: 2,
        answerKey: "q3a2",
        pieType: PieType.CLASSIC,
        imageUrl: "/images/question3/cumin.avif",
        imageAlt: "Cumin seeds",
      },
      {
        id: 3,
        answerKey: "q3a3",
        pieType: PieType.POTATO,
        imageUrl: "/images/question3/cinnamon.avif",
        imageAlt: "Cinnamon sticks",
      },
      {
        id: 4,
        answerKey: "q3a4",
        pieType: PieType.PUMPKIN,
        imageUrl: "/images/question3/garlic.avif",
        imageAlt: "Garlic cloves",
      },
    ],
  },
  {
    id: 4,
    questionKey: "question4",
    answerOptions: [
      {
        id: 1,
        answerKey: "q4a1",
        pieType: PieType.POTATO,
        imageUrl: "/images/question4/suzani-flowers.png",
        imageAlt: "Suzani flower embroidery",
      },
      {
        id: 2,
        answerKey: "q4a2",
        pieType: PieType.PUMPKIN,
        imageUrl: "/images/question4/ikat-waves.png",
        imageAlt: "Ikat textile pattern",
      },
      {
        id: 3,
        answerKey: "q4a3",
        pieType: PieType.CHEESE,
        imageUrl: "/images/question4/geometric-tiles.png",
        imageAlt: "Tiled wall with patterns",
      },
      {
        id: 4,
        answerKey: "q4a4",
        pieType: PieType.LAMB,
        imageUrl: "/images/question4/gold-thread.png",
        imageAlt: "Gold embroidery detail",
      },
    ],
  },
  {
    id: 5,
    questionKey: "question5",
    answerOptions: [
      {
        id: 1,
        answerKey: "q5a1",
        pieType: PieType.PUMPKIN,
        imageUrl: "/images/question5/breath.avif",
        imageAlt: "Person meditating calmly",
      },
      {
        id: 2,
        answerKey: "q5a2",
        pieType: PieType.POTATO,
        imageUrl: "/images/question5/laugh.avif",
        imageAlt: "Laughing child",
      },
      {
        id: 3,
        answerKey: "q5a3",
        pieType: PieType.LAMB,
        imageUrl: "/images/question5/angry.avif",
        imageAlt: "Angry eagle",
      },
      {
        id: 4,
        answerKey: "q5a4",
        pieType: PieType.CLASSIC,
        imageUrl: "/images/question5/help-others.jpg",
        imageAlt: "Woman wiping the tears of a crying woman",
      },
    ],
  },
  {
    id: 6,
    questionKey: "question6",
    answerOptions: [
      {
        id: 1,
        answerKey: "q6a1",
        pieType: PieType.LAMB,
        imageUrl: "/images/question6/lagman.jpg",
        imageAlt: "Hot bowl of lagman",
      },
      {
        id: 2,
        answerKey: "q6a2",
        pieType: PieType.CLASSIC,
        imageUrl: "/images/gallery/uzbek-bread.avif",
        imageAlt: "Bread",
      },
      {
        id: 3,
        answerKey: "q6a3",
        pieType: PieType.POTATO,
        imageUrl: "/images/gallery/samsa.avif",
        imageAlt: "Warm samsa pastry",
      },
      {
        id: 4,
        answerKey: "q6a4",
        pieType: PieType.PUMPKIN,
        imageUrl: "/images/question6/pumpkin-soup.avif",
        imageAlt: "Pumpkin soup bowl",
      },
    ],
  },
  {
    id: 7,
    questionKey: "question7",
    answerOptions: [
      {
        id: 1,
        answerKey: "q7a1",
        pieType: PieType.CHEESE,
        imageUrl: "/images/question7/green.avif",
        imageAlt: "Mint tea in cup",
      },
      {
        id: 2,
        answerKey: "q7a2",
        pieType: PieType.CLASSIC,
        imageUrl: "/images/question2/tea.avif",
        imageAlt: "Black tea",
      },
      {
        id: 3,
        answerKey: "q7a3",
        pieType: PieType.PUMPKIN,
        imageUrl: "/images/question7/ginger-tea.avif",
        imageAlt: "Lemon ginger tea",
      },
      {
        id: 4,
        answerKey: "q7a4",
        pieType: PieType.POTATO,
        imageUrl: "/images/question7/fruit-tea.avif",
        imageAlt: "Fruit tea with dried fruits",
      },
    ],
  },
  {
    id: 8,
    questionKey: "question8",
    answerOptions: [
      {
        id: 1,
        answerKey: "q8a1",
        pieType: PieType.POTATO,
        imageUrl: "/images/question8/cozy.avif",
        imageAlt: "Cozy bedroomw ith book, candle and cup of tea",
      },
      {
        id: 2,
        answerKey: "q8a2",
        pieType: PieType.PUMPKIN,
        imageUrl: "/images/question8/messy-home.avif",
        imageAlt: "Living room with many items",
      },
      {
        id: 3,
        answerKey: "q8a3",
        pieType: PieType.CLASSIC,
        imageUrl: "/images/question8/minimalist-home.avif",
        imageAlt: "Minimalist space with plant and wall clock",
      },
      {
        id: 4,
        answerKey: "q8a4",
        pieType: PieType.LAMB,
        imageUrl: "/images/question8/bold-home.avif",
        imageAlt: "Bold home decor",
      },
    ],
  },
  {
    id: 9,
    questionKey: "question9",
    answerOptions: [
      {
        id: 1,
        answerKey: "q9a1",
        pieType: PieType.CLASSIC,
        imageUrl: "/images/question9/wise.avif",
        imageAlt: "Master Yoda",
      },
      {
        id: 2,
        answerKey: "q9a2",
        pieType: PieType.CHEESE,
        imageUrl: "/images/question9/weird-brilliant.avif",
        imageAlt: "Statue with seagul sitting on its head",
      },
      {
        id: 3,
        answerKey: "q9a3",
        pieType: PieType.POTATO,
        imageUrl: "/images/question9/loving.avif",
        imageAlt: "Cute cat",
      },
      {
        id: 4,
        answerKey: "q9a4",
        pieType: PieType.CHEESE,
        imageUrl: "/images/question9/energetic.avif",
        imageAlt: "Dancing in joy",
      },
    ],
  },
  {
    id: 10,
    questionKey: "question10",
    answerOptions: [
      {
        id: 1,
        answerKey: "q10a1",
        pieType: PieType.CLASSIC,
        imageUrl: "/images/question10/triangle.jpg",
        imageAlt: "Triangle samsa",
      },
      {
        id: 2,
        answerKey: "q10a2",
        pieType: PieType.POTATO,
        imageUrl: "/images/question10/round.jpg",
        imageAlt: "Round samsa",
      },
      {
        id: 3,
        answerKey: "q10a3",
        pieType: PieType.LAMB,
        imageUrl: "/images/question10/spiral.jpg",
        imageAlt: "Spiral pastry",
      },
      {
        id: 4,
        answerKey: "q10a4",
        pieType: PieType.CHEESE,
        imageUrl: "/images/question10/square.jpg",
        imageAlt: "Square samsa",
      },
    ],
  },
];
